### PR TITLE
Add some nice code from others fork

### PR DESCRIPTION
**Pull request by simbus82**

### CODE REVIEW

**Comment by toonvd** [comment]
Some of these are not well coded. These have to be reviewed..

**Comment by simbus82** [comment]
obviously! but it is a "reminder" ;-) There are many interesting forks  ...

**Comment by toonvd** [comment]
@jeroenvermeulen let's take a look at these when we have time?

**Comment by jeroenvermeulen** [comment]
Ouch...  such a "bulk" pull request is not such a good practise.
We would really need small pull requests only addressing one bug of feature.
If you send us small PRs we will check and merge if everything is OK.
We will try to process small PRs within one week.

**Comment by simbus82** [comment]
Oh sorry :-( you are right!

**Pull request closed without merging**
